### ISSUE TITLE
Nedaří se mi buildnout Dockerfile

### ISSUE THREAD

**Issue by westfood** [WebarchivCZ/WA-KAT#107]
Zkoušel jsem buildnout kat z několika verzí Ubuntu (16, 18, 20 myslím). Ale selhal jsem!

Čichám, že je někde problém s Python 2.7.. Ale víc jsem se v tom nevrtal.

Kdyby jsi měl někdy čas, wa-kat nasazujeme jako kontejner. Zatím používám nějaký image co vytvořil @horakjirinkp, ale neumím ten build reprodukovat.

```
Collecting setuptools (from bottle-rest==0.4.1->wa-kat)
  Downloading https://files.pythonhosted.org/packages/82/2f/ef7afd98530d07c89deffec833b4b1a91a27a5db6d9f1a216599f5f0316e/setuptools-51.1.2.tar.gz (2.1MB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "setuptools/__init__.py", line 16, in <module>
        import setuptools.version
      File "setuptools/version.py", line 1, in <module>
        import pkg_resources
      File "pkg_resources/__init__.py", line 1365
        raise SyntaxError(e) from e
                                ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-QDq2W7/setuptools/
You are using pip version 8.1.1, however version 20.3.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
The command '/bin/sh -c pip install -U wa-kat' returned a non-zero code: 1
```

**Comment by Bystroushaak** [comment]
Zkusím na to mrknout.

**Comment by westfood** [comment]
@Bystroushaak furt mám issue:

```
Collecting joblib (from nltk>=3.1->textblob==0.11.1->wa-kat)
  Downloading https://files.pythonhosted.org/packages/69/a1/68266edcfabe8dc240d7c9e06972a121b011b232f0d1796a016192438435/joblib-1.0.0.tar.gz (315kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-HyRBHC/joblib/setup.py", line 4, in <module>
        import pathlib
    ImportError: No module named pathlib

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-HyRBHC/joblib/
You are using pip version 8.1.1, however version 20.3.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
The command '/bin/sh -c pip install -U wa-kat' returned a non-zero code: 1
```

**Comment by westfood** [comment]
Ty to testuješ ve svým prostředí, žejo?

**Comment by Bystroushaak** [comment]
Ne, v dockeru. Ale pořád to není vyřešené.

**Comment by Bystroushaak** [comment]
Tak jo, manuálně jsem pinnul různé knihovny na starší verze, které ještě podporují Python 2.7. Chtělo by to přepis na 3.x, protože 2.7 už je oficiálně nepodporovaný a tohle se bude horšit. Ale pokud si vybuildíš tu image a někde si jí schováš, tak by měla fungovat donekonečna.

**Comment by Bystroushaak** [comment]
Jinak jsem to zkoušel teď zbuildit v tom Dockerfile co je v rootu a běží jak build, tak i run.
