### ISSUE TITLE
zeo a supervisor

### ISSUE THREAD

**Issue by westfood** [WebArchivCZ/WA-KAT#82]
ZEO mi hází ze supervisoru chybovku, z příkazový řádky je to v pohodě (tedy, nevypisuje vůbec nic).

Něco jsem asi zase přehlédl;-)

```
AttributeError: ZEOServer instance has no attribute 'server'
Traceback (most recent call last):
  File "/usr/bin/runzeo", line 9, in <module>
    load_entry_point('ZEO==4.1.0', 'console_scripts', 'runzeo')()
  File "/usr/lib/python2.7/site-packages/ZEO/runzeo.py", line 394, in main
    s.main()
  File "/usr/lib/python2.7/site-packages/ZEO/runzeo.py", line 165, in main
    self.server.close()
AttributeError: ZEOServer instance has no attribute 'server'

[program:runzeo]
command=sh -c 'runzeo -C $(python -c "from wa_kat.settings import *; print ZEO_SERVER_PATH")'
environment=SETTINGS_PATH="/opt/wa_kat.json"
autostart=true
user=uwsgi
redirect_stderr=true

[program:wa-kat]
command=wa_kat_server.py
environment=SETTINGS_PATH="/opt/wa_kat.json"
user=uwsgi
autostart=true
autorestart=true
stdout_logfile=/var/log/wa-kat/stdout.log
stderr_logfile=/var/log/wa-kat/sterr.log
redirect_stderr=true
stopsignal=QUIT
```

**Comment by Bystroushaak** [comment]
Zkus v konzoli evalnout to ``$(python -c "from wa_kat.settings import *; print ZEO_SERVER_PATH")`` a případně sudo pip install -U ZEO.

**Comment by westfood** [comment]
Hele, udělal jsem rebuild celého stroje a už to jede..
