### ISSUE TITLE
divná chyba

### ISSUE THREAD

**Issue by westfood** [WebarchivCZ/WA-KAT#95]
```
[root@war WA-KAT]# docker run -p 10001:8080 -it wakat-1.1.7
Stopping supervisor: supervisord.
Starting supervisor: supervisord.
Traceback (most recent call last):
  File "/usr/local/bin/wa_kat_server.py", line 15, in <module>
    from wa_kat import rest_api  # for Bottle applications
  File "/usr/local/lib/python2.7/dist-packages/wa_kat/rest_api/__init__.py", line 23, in <module>
    import db
  File "/usr/local/lib/python2.7/dist-packages/wa_kat/rest_api/db.py", line 17, in <module>
    from ..db.request_info import RequestInfo
  File "/usr/local/lib/python2.7/dist-packages/wa_kat/db/request_info.py", line 14, in <module>
    from ..logger import logger
  File "/usr/local/lib/python2.7/dist-packages/wa_kat/logger.py", line 130, in <module>
    logger = Logger()
  File "/usr/local/lib/python2.7/dist-packages/wa_kat/logger.py", line 44, in __init__
    "settings.LOG_TO_SENTRY==True, but SENTRY_DSN property is not "
  File "/usr/local/lib/python2.7/dist-packages/wa_kat/logger.py", line 115, in error
    self._log(msg, long_msg=long_msg, level="error", url=url)
  File "/usr/local/lib/python2.7/dist-packages/wa_kat/logger.py", line 58, in _log
    self._log_to_udp(logged_obj)
  File "/usr/local/lib/python2.7/dist-packages/wa_kat/logger.py", line 77, in _log_to_udp
    sock.sendto(as_json, self.address_pair)
socket.gaierror: [Errno -3] Temporary failure in name resolution
```

**Comment by westfood** [comment]
```
(seeder) [rudolf@war Seeder]$ cat /opt/wa_kat.json
{
    "WEB_ADDR": "0.0.0.0",
    "WEB_PORT": "10001",
    "SEEDER_TOKEN": "nějakýtoken"
    "SENTRY_DSN": "http://nějaképkelnéuid@sentry.webarchiv.cz/5"
}
```

**Comment by westfood** [comment]
ale teď přemýšlím proč by ten docker image vůbec koukal na /opt/wa_kat.json

**Comment by Bystroushaak** [comment]
Mrknu na to a opravím.

**Comment by Bystroushaak** [comment]
Vydal jsem novou verzi, tam by se tohle už stávat nemělo.

**Comment by westfood** [comment]
Díky, nahoidl jsem 1.1.8
